config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :messages, only: [:new, :create]
  end
  resources :plants, except: [:destroy]
  resources :friendships
  resources :messages, only: [:index, :show]
  
  get "/", to: 'users#home'
  # get "/messages", to: 'users#comingsoon'

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#logout"

  get "/plants/new", to: "plants#index"
  get "/plants/:id/water", to: "plants#water"
  get "/plants/:id/feed", to: "plants#feed"
  get "/plants/:id/sun", to: "plants#sun"

  get "/users/:id/add-friend", to: "friend_requests#create"
  get "/users/:id/remove-friend", to: "friendships#destroy"
  
  get "/friendships/:id/accept-request", to: "friend_requests#update"
  get "friendships/:id/deny-request", to: "friend_requests#destroy"
  get "friendships/:id/destroy", to: "friendships#destroy"
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :recipient, class_name: "User", foreign_key: "recipient_id"
    belongs_to :sender, class_name: "User", foreign_key: "sender_id"
    scope :unread, -> { where read: false }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :set_recipient, only: [:new, :create]

    ### shows all of the current user's received messages ###

    def index
        @messages = current_user.messages
    end

    ### shows all of the current user's sent messages ###

    def show
        @messages = current_user.sent_messages
    end

    ### creates a new message, sets the recipient id, and adds the message to the recipient's messages ###

    def new
        @message = current_user.sent_messages.new
    end

    def create
        @message = current_user.sent_messages.new(message_params)
        @message.recipient_id = params[:message][:recipient_id]
        @message.save
        @message.recipient.messages << @message
        redirect_to messages_path
    end

    private

    def message_params
        params.require(:message).permit(:content, :recipient_id, :sender_id)
    end

    def set_recipient
        @recipient = User.find params[:user_id]
    end
end

app/views/messages/index.html.erb
<div>
    <a href="<%= new_user_message_path(current_user) %>"><button style="margin-top: 25px; margin-right: 70px; float: right; display: inline-block;">Compose New</button></a>
    <h1 style="margin-left: 60px; float: left; margin-left: 60px;">Received Messages</h1>
    <p style="margin-right: 30px; margin-top: 32px; float: right;"><%= link_to "Sent Messages", message_path(current_user) %></p>
</div>
<div style="text-align: center;">
    <div style="border: solid; border-width: 1px; min-height: 480px; display: inline-block; width: 90%; padding: 20px;">
        <% if current_user.messages == [] %>
            <h3 style="margin-top: 75px;">You have no message history.</h3>
        <% else %>
            <% @messages.order(created_at: :desc).each do |message| %>
                <div style="border: dotted; border-width: 1px; width: 90%; min-height: 150px; padding: 15px; display: inline-block;">
                    <div class="column-left" style="margin-top: 15px;">
                        To: <%= link_to message.recipient.username, user_path(message.recipient) %><br>
                        From: <%= link_to message.sender.username, user_path(message.sender) %><br><br>
                        <%= message.created_at.strftime("%d-%m-%Y") %><br>
                        <%= message.created_at.strftime("%I:%M %P") %>
                    </div>
                    <div class="column-right" style="margin-top: 10px; text-align: left; min-height: 100px; margin-bottom: 10px;">
                        <b>Message:</b><br>
                        <%= message.content %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/messages/new.html.erb
<div style="padding: 20px; margin-left: 80px;">
    <%= render partial: "layouts/error_list", locals: {new_object: @message} %>
    <%= form_for @message, url: user_messages_path do |f| %>
        <h2>Compose A New Message</h2>
        From: <%= current_user.username %><br><br>

        <%= f.label :recipient_id, "To: "%>
        <%= f.collection_select :recipient_id, current_user.friends, :id, :username %> <%= "(You can only message friends!)" if current_user.friends.empty? %><br><br>


        <%= f.label :content, "Message"%><br>
        <%= f.text_area :content, size: "70x10" %><br><br><br>
        
        <%= f.submit 'Send Message' %><br><br><br>
    <% end %>
</div>

app/views/messages/show.html.erb
<div>
    <a href="<%= new_user_message_path(current_user) %>"><button style="margin-top: 25px; margin-right: 70px; float: right; display: inline-block;">Compose New</button></a>
    <h1 style="margin-left: 60px; float: left; margin-left: 60px;">Sent Messages</h1>
    <p style="margin-right: 30px; margin-top: 32px; float: right;"><%= link_to "Recieved Messages", messages_path %></p>
</div>
<div style="text-align: center;">
    <div style="border: solid; border-width: 1px; min-height: 480px; display: inline-block; width: 90%; padding: 20px;">
        <% if current_user.sent_messages == [] %>
            <h3 style="margin-top: 75px;">You haven't sent any messages!</h3>
        <% else %>
            <% @messages.order(created_at: :desc).each do |message| %>
                <div style="border: dotted; border-width: 1px; width: 90%; min-height: 150px; padding: 15px; display: inline-block;">
                    <div class="column-left" style="margin-top: 15px;">
                        To: <%= link_to message.recipient.username, user_path(message.recipient) %><br>
                        From: <%= link_to message.sender.username, user_path(message.sender) %><br><br>
                        <%= message.created_at.strftime("%d-%m-%Y") %><br>
                        <%= message.created_at.strftime("%I:%M %P") %>
                    </div>
                    <div class="column-right" style="margin-top: 10px; text-align: left; min-height: 100px; margin-bottom: 10px;">
                        <b>Message:</b><br>
                        <%= message.content %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>