config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :messages, only: [:new, :create]
  end
  resources :plants, except: [:destroy]
  resources :friendships
  resources :messages, only: [:index, :show]
  
  get "/", to: 'users#home'
  # get "/messages", to: 'users#comingsoon'

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#logout"

  get "/plants/new", to: "plants#index"
  get "/plants/:id/water", to: "plants#water"
  get "/plants/:id/feed", to: "plants#feed"
  get "/plants/:id/sun", to: "plants#sun"

  get "/users/:id/add-friend", to: "friend_requests#create"
  get "/users/:id/remove-friend", to: "friendships#destroy"
  
  get "/friendships/:id/accept-request", to: "friend_requests#update"
  get "friendships/:id/deny-request", to: "friend_requests#destroy"
  get "friendships/:id/destroy", to: "friendships#destroy"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :friend_requests, dependent: :destroy
    has_many :pending_friends, through: :friend_requests, source: :friend
    has_many :friendships, dependent: :destroy
    has_many :friends, through: :friendships
    has_many :messages, class_name: "Message", foreign_key: "recipient_id"
    has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"

    has_secure_password
    validates :password, length: { minimum: 6 }, :if => :password
    validates :username, presence: true, uniqueness: true
    validates :profile_pic, presence: true

    has_many :plants
    has_many :care_actions

# removes friend

    def remove_friend(friend)
        current_user.friends.destroy(friend)
    end

# creates full name

    def full_name
        self.first_name + " " + self.last_name
    end

# calculates age

    def age
        now = DateTime.now
        created = self.created_at
        age = (now.to_date - created.to_date).to_i
        if age == 1
            "#{age} day old"
        else
            "#{age} days old"
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authorized, only: [:show, :edit, :update]
    before_action :depreciate, only: [:index, :show]

    def home
    end

    ### lets a user search for other users with the params[:search] function before displaying/sorting results ###
    ### if there is no search action performed, it just displays/sorts all users ###

    def index
        if params[:search]
            @users = User.where('username LIKE ?', "%#{params[:search]}%").order('id DESC')
        else
            @users = User.where.not(id: session[:user_id]).order('id DESC')
        end
        @user = User.find_by(id: session[:user_id])
    end

    ### displays a specific user and their plants ###

    def show
        @user = User.find_by(id: params[:id])
            if @user == nil
                redirect_to users_path
            end
        @plants = Plant.where(user_id: params[:id])
    end

    ### creates a new user with a random-stat generated plant. users cannot exist without a plant! ###

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        
        if @user.valid?
            @user.save
            plant = Plant.new
            plant.random
            plant.user_id = @user.id
            plant.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    ### edits a user's full name, email, pass, profile picture, and bio ###

    def edit
        @user = User.find_by(id: session[:user_id])
    end

    def update
        @user = User.find_by(id: session[:user_id])
        @user.update(user_params)
        redirect_to user_path(@user)
    end

    ### destroys a user but not their plants - want to add a greenhouse feature for forfeited plants ###

    def destroy
        @user = current_user
        @user.destroy
        session.destroy
        redirect_to '/login'
    end

    private

    def user_params
        params.require(:user).permit(:username, :password, :email, :first_name, :last_name, :bio, :profile_pic, :search)
    end

    ### plants depreciate on render to make sure all stats are up-to-date ###

    def depreciate
        plants = Plant.where(user_id: params[:id])
        plants.each do |plant|
            plant.happiness = plant.happiness - plant.elapsed_time
            plant.health = plant.health - plant.elapsed_time
            plant.hunger = plant.hunger - plant.elapsed_time
            plant.save
        end
    end
end

app/views/users/comingsoon.html.erb
<div class="coming-soon-image"><%= image_tag("still-growing.gif") %></div>
<div style="text-align: center; margin-top: 50px;">
    <h1>This feature is still under construction.</h1>
    <h2>You'll be able to message your friends soon!!!</h2>
</div>

app/views/users/edit.html.erb
<br>
<div class="row">
    <div class="column-left">
        <div class="profile-picture" style="text-align: center; margin-top: 73px;">
            <img src="<%= @user.profile_pic %>">
        </div>
        <div style="margin-top: 20px; text-align: center;">
            <% if @user.first_name && @user.last_name %>
                <h3><%= @user.full_name %></h3>
            <% end %>
            <% if @user.bio %>
                <p><%= @user.bio %></p>
            <% end %><br>
        </div>
    </div>

    <div class="column-right">
        <div style="margin-left: 40px;">
            <%= render partial: "layouts/error_list", locals: {new_object: @user} %>
            <%= form_for @user do |f| %>
                <h3>Edit Your Public Profile: </h3>
                <%= f.label :first_name %><br>
                <%= f.text_field :first_name, size: 20 %><br><br>

                <%= f.label :last_name %><br>
                <%= f.text_field :last_name, size: 20 %><br><br>

                <%= f.label :bio %><br>
                <%= f.text_area :bio, size: "30x4" %><br><br>

                <%= f.label :profile_pic, "Profile Picture URL"%><br>
                <%= f.text_field :profile_pic, size: 50 %><br><br><br>

                <%= f.submit 'Edit Profile' %>
            <% end %><br><br><br>

            <%= form_for @user do |f| %>
                <h3>Update Account Information:</h3>

                <%= f.label :email %><br>
                <%= f.text_field :email, size: 30 %><br><br>

                <%= f.label :password %><br>
                <%= f.password_field :password, size: 20 %><br><br><br>
                
                <%= f.submit 'Update Account' %><br><br><br>
            <% end %>
        </div>

        <div style="float:right; margin-right: 20px;">
            <%= link_to "Delete Account", @user, method: :delete, data: { confirm: "Are you sure? This can't be undone." } %>
        </div>

    </div>
</div>

app/views/users/home.html.erb
<div class="home-page-image"><%= image_tag("home-page-photo.jpg") %></div>
<div style="text-align: center">
    <div style="display: inline-block;">
        <h3 style="text-align: left;"><i>What is BioPlants?</i></h3>
        <p style="text-align: left;"> BioPlants is an interactive web-based game where you take care of plants by feeding, watering, and putting them in sunlight!<br>
        You can have up to six plants! To create a new plant, you'll have to propogate one of your existing plants.<br><br>
        Designed by Alexandria Pugia, this game was created to bring joy to friends and family (espsecially those that struggle to keep real plants alive!)<br>
        The higher your plant's resilience, the slower they wilt!<br>
        <br>
        Sign up to start playing! We are so happy you're here and can't wait for you to love your virtual plants as much as we do!</p>
        <br>
        <h3 style="text-align: left;"><i>What is in BioPlant's future?</i></h3>
        <p style="text-align: left;"> We hope to impliment a digital currency and add a public forum where you can advertise plants for sale or for trade!</p>
    </div>
</div>

app/views/users/index.html.erb
<br>
<% if current_user %>

    <div class="column-left">
        <p style="text-align: center; margin-top: 26px;">Here's how you look to others:</p>
        <a href="<%= user_path(@user.id) %>">
            <div class="profile-picture" style="text-align: center; margin-top: 25px;">
                <img src="<%= @user.profile_pic %>">
            </div>
            <div style="margin-top: 20px; text-align: center;">
                <h3><%= @user.username %></h3></a>
                <p><%= @user.friendships.count %> Friends<p>
            </div>
    </div>

    <div class="column-right" style="margin-bottom: 40px;">
        <div class="row" style="border: solid; border-width: 1px; padding: 20px; margin-right: 50px;">
            <div style="margin-bottom: 80px;">
                <h1 style="float: left; margin-left: 40px;">All Users</h1>

                <div style="float: right; margin-right: 25px; margin-top: 25px;">
                    <%= form_tag(users_path, method: :get) do %>
                        <%= text_field_tag :search %>
                        <%= submit_tag 'Search' %>
                    <% end %>
                </div>
            </div>

            <% @users.each do |user| %>
                <a href="<%= user_path(user) %>">
                    <div class="column">
                        <div class="profile-picture" style="text-align: center; margin-top: 25px;">
                            <img src="<%= user.profile_pic %>"><br>
                        </div>
                        <div style="text-align: center;">
                            <h3><%= user.username %></h3></a>
                            <p><%= user.friendships.count %> Friends<p>
                        </div>
                    </div>
            <% end %>
        </div>
    </div>

<% else %>

    <div class="home-page-image">
        <%= image_tag("sad-cloud.gif") %>
    </div>
    <div style="text-align: center; margin-top: 100px;">
        <h3>You must be signed in to view your profile!</h3>
        <br>
        <h3><%= link_to "log in", '/login' %> or <%= link_to "sign up", new_user_path %></h3>
    </div>

<% end %>

app/views/users/new.html.erb
<br><br><br>
<div style="text-align: center;">  
    <div style="display: inline-block; background-color: #ececec; width: 400px; height: auto;">
        <h1 style="margin-top: 50px;">Please Sign Up Below</h1><br>

        <%= render partial: "layouts/error_list", locals: {new_object: @user} %>
        <%= form_for @user do |f| %>
            <%= f.label :username %><br>
            <%= f.text_field :username %><br><br>
            <%= f.label :email %><br>
            <%= f.text_field :email %><br><br>
            <%= f.label :password %><br>
            <%= f.password_field :password %><br><br>
            <%= label_tag :password_confirmation%><br>
            <%= password_field_tag :password_confirmation%><br><br><br>
            <%= f.submit %><br><br><br>
        <% end %>
    </div>
    <h4><%= link_to "login instead", login_path %></h4>
</div>

app/views/users/show.html.erb
<br>
<div class="row">
    <div class="column-left">
        <div style="margin-top: 73px;"></div>
            <div class="profile-picture" style="text-align: center; margin-top: 40px;">
                <img src="<%= @user.profile_pic %>">
            </div>
            <div style="margin-top: 20px; text-align: center;">
                <% if @user.first_name && @user.last_name %>
                    <h3><%= @user.full_name %></h3>
                <% end %>

                <% if @user.bio %>
                    <p style="width: 95%; margin: auto; text-align: center;"><i><%= @user.bio %></i></p><br>
                <% end %>

                <% if @user.id != session[:user_id] %>
                    <% if Friendship.find_by(user_id: session[:user_id], friend: @user) %>
                        <a href="<%= @user.id %>/remove-friend"><button><p style="margin-left: 12px; margin-right: 12px;">Remove Friend</p></button></a>
                    <% elsif FriendRequest.find_by(user_id: session[:user_id], friend_id: @user.id) %>
                        <button><p style="margin-left: 12px; margin-right: 12px;">Request Pending...</p></button>
                    <% else %>
                        <a href="<%= @user.id %>/add-friend"><button><p style="margin-left: 12px; margin-right: 12px;">Add Friend</p></button><a>
                    <% end %>
                <% end %>

                <p><%= @user.friendships.count %> Friends</p>

                <% if @user.id == session[:user_id] %>
                    <br><br>
                    <%= link_to "Edit Profile", edit_user_path(current_user) %>
                <% end %>
            </div>
        </div>

    <div class="column-right">
        <h1 style="text-align: left; font-size: 250%;"><%= @user.username.upcase %></h1>

        <div style="margin-left: 30px; margin-top: 30px;">
            <h3>Plants Owned: <%= @plants.count %></h3>
            <% if @user.plants != [] %>
                <h3>Overall Plant Happiness: <%= (@plants.map { |plant| plant.stat_total }.sum) / @plants.count %>%</h3>
            <% end %> 

        <div class="row" style="border: solid; border-width: 1px; padding: 20px; margin-top: 50px; margin-right: 50px;">
            <div class="row">
            <% @plants.each do |plant| %>
            <% if @plants.count == 1 %>
                <div class="single-plant">
            <% elsif @plants.count == 2 %>
                <div class="two-plants">
            <% else %>
                <div class="many-plants">
            <% end %>
                    <% if plant.nickname == nil || plant.nickname == "" %>
                        <div style="margin-top: 74px;"></div>
                    <% else %>
                        <h1><i><%= plant.nickname %></i></h1>
                    <% end %>
                        <% if plant.stat_total >= 70 %>
                            <div class="profile-picture"><a href="<%= plant_path(plant) %>"><%= image_tag("happy.jpg") %></a></div>
                        <% else %>
                            <div class="profile-picture"><a href="<%= plant_path(plant) %>"><%= image_tag("sad.jpeg") %></a></div>
                        <% end %>
                    <h3>~ <%= plant.name %> ~</h3>
                    <p>Health: <%= plant.health %></p>
                    <p>Happiness: <%= plant.happiness %></p>
                    <p>Hunger: <%= plant.hunger %></p>
                </div>
            <% end %>
        </div>
    </div>

            <% if @user.id == session[:user_id] %>
                <br><br><br>
                Your account is <%= @user.age %> and was created on <%= @user.created_at.strftime("%B %d, %Y at %I:%M %p") %>
                <br>
            <% end %>
        </div>
    </div>
</div>