config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :messages, only: [:new, :create]
  end
  resources :plants, except: [:destroy]
  resources :friendships
  resources :messages, only: [:index, :show]
  
  get "/", to: 'users#home'
  # get "/messages", to: 'users#comingsoon'

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#logout"

  get "/plants/new", to: "plants#index"
  get "/plants/:id/water", to: "plants#water"
  get "/plants/:id/feed", to: "plants#feed"
  get "/plants/:id/sun", to: "plants#sun"

  get "/users/:id/add-friend", to: "friend_requests#create"
  get "/users/:id/remove-friend", to: "friendships#destroy"
  
  get "/friendships/:id/accept-request", to: "friend_requests#update"
  get "friendships/:id/deny-request", to: "friend_requests#destroy"
  get "friendships/:id/destroy", to: "friendships#destroy"
end

app/models/plant.rb
class Plant < ApplicationRecord
    belongs_to :user
    has_many :care_actions
    has_many :actions, through: :care_actions

    validates :nickname, length: { maximum: 13 }

    ### calculates stat total as a percentage (out of 100%) ###

    def stat_total
        (self.health + self.hunger + self.happiness) / 3
    end

    ### details ###

    def age
        now = DateTime.now.in_time_zone('UTC')
        created = self.created_at
        age = (now.to_date - created.to_date).to_i
        if age == 1
            "#{age} day old"
        else
            "#{age} days old"
        end
    end

    def description
        self.name + " - " + self.resilience.to_s
    end

    ### random stat generator for new plant ###

    def random_resilience_generator
        self.resilience = 10.times.sum{ Random.rand(1..13) } 
    end

    def random_plant_type
        plant_types = ["Moss", "Flower", "Fern", "Succulent"]
        plant_types[Random.rand(0..3)]
    end

    def random
        self.name = random_plant_type
        self.resilience = random_resilience_generator
    end

    def propogate_random(prop_plant_id)
        self.name = random_plant_type
        prop_plant = Plant.find_by(id: prop_plant_id)
        sum = (10.times.sum{ Random.rand(1..13) } + prop_plant.resilience) / 2
        self.resilience = sum
    end

    ### actions to improve plant wellness ###

    def random_status_number_generator
        Random.rand(1..10)
    end
    
    def water_plant
        self.health += random_status_number_generator
        if self.health > 100
            self.health = 100
        end
        self.save
    end

    def feed_plant
        self.hunger += random_status_number_generator
        if self.hunger > 100
            self.hunger = 100
        end
        self.save
    end

    def sun_plant
        self.happiness += random_status_number_generator
        if self.happiness > 100
            self.happiness = 100
        end
        self.save
    end

    ### depreciates overall wellness ###

    def elapsed_time
        now = DateTime.now.in_time_zone('UTC')
        updated = self.updated_at
        time = ((now.to_time - updated.to_time) / (self.resilience * 100)).to_i
        (time / (random_status_number_generator * 0.5)).round
    end

    def depreciate
        self.happiness = (self.happiness - self.elapsed_time)
            if self.happiness <= 0
                self.happiness = 0
            end
        self.health = (self.health - self.elapsed_time)
            if self.health <= 0
                self.health = 0
            end
        self.hunger = (self.hunger - self.elapsed_time)
            if self.hunger <= 0
                self.hunger = 0
            end
        self.save
    end

    ### to reset all plants back to 100% happy - used for testing depreciation ###

    # def make_better
    #     self.happiness = 100
    #     self.health = 100
    #     self.hunger = 100
    #     self.save
    # end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

    ### shows all of the user's plants + shows a new plant form for propogating ###

    def index
        @plants = Plant.where(user_id: session[:user_id])
        @plants.each { |plant| plant.depreciate }
        @plant = Plant.new
    end

    ### checks to see if a user has less than 6 plants before propogating a new one ###

    def propogate
        if current_user.plants.count < 6
            @plant = Plant.new
            @plant.propogate_random
            @plant.user_id = session[:user_id]
            @plant.save
        end
        redirect_to plant_path(@plant)
    end

    ### shows the plant and depreciates it's stats ###

    def show
        @plant = Plant.find_by(id: params[:id])
        @plant.depreciate
        @user = current_user
    end

    ### workaround for no javascript - care actions are performed by redirecting to a page that ###
    ### performs an action before redirecting back ###

    def water
        plant = Plant.find_by(id: params[:id])
        plant.water_plant
        CareAction.create(plant_id: plant.id, user_id: current_user.id, action_id: 1)
        redirect_to plant_path(plant)
    end

    def feed
        plant = Plant.find_by(id: params[:id])
        plant.feed_plant
        CareAction.create(plant_id: plant.id, user_id: current_user.id, action_id: 2)
        redirect_to plant_path(plant)
    end

    def sun
        plant = Plant.find_by(id: params[:id])
        plant.sun_plant
        CareAction.create(plant_id: plant.id, user_id: current_user.id, action_id: 3)
        redirect_to plant_path(plant)
    end

    ### creates a new plant with random stats ###

    def new
        @plant = Plant.new
    end

    def create
        @plant = Plant.new(user_id: current_user.id)
        @plant.propogate_random(params[:plant][:id])
        
        if @plant.save
            redirect_to plant_path(@plant)
        else
            redirect_to plants_path
        end
    end

    ### allows a user to update the nickname of a plant ###

    def edit
        @plant = Plant.find_by(id: params[:id])
    end

    def update
        @plant = Plant.find_by(id: params[:id])
        if @plant.update(plant_params)
            redirect_to plant_path(@plant)
        else
            render :edit
        end
    end

    private

    def plant_params
        params.require(:plant).permit(:nickname)
    end
end

app/views/plants/edit.html.erb
<div class="row">
    <% if @plant.nickname != "" && @plant.nickname != nil %>
        <h1 style="margin-top: 39px; text-align: center;"><i><%= @plant.nickname %>, the <%= @plant.name %> plant</i></h1>
    <% else %>
        <h1 style="margin-top: 39px; text-align: center;"><i><%= @plant.name %></i></h1>
    <% end %>

    <div class="column-left">
        <div class="profile-picture" style="text-align: center; margin-top: 0px;">
            <% if @plant.stat_total >= 70 %>
                <div class="profile-picture"><%= image_tag("happy.jpg") %></div>
            <% else %>
                <div class="profile-picture"><%= image_tag("sad.jpeg") %></div>
            <% end %>
            <h3>~ <%= @plant.name %> ~</h3><br>
            Health Status: <%= @plant.stat_total %>%<br>
            Resilience: <%= @plant.resilience %><br>
        </div>
    </div>

    <div class="column-right">
        <div style="border: solid; border-width: 1px; padding: 20px; margin-right: 50px; margin-top: 30px;">
        <%= render partial: "layouts/error_list", locals: {new_object: @plant} %>
            <%= form_for @plant do |f| %>
                <%= f.label :nickname %><br>
                <%= f.text_field :nickname %><br><br>
                <%= f.submit "Update"%>
            <% end %>
        </div>
    </div>
</div>

app/views/plants/index.html.erb
<br>
<% if current_user %>

    <h1 style="text-align: center;">Plants</h1>
    <h2 style="margin-left: 50px;">Propogate</h2>
        <div class="row" style="border: solid; border-width: 1px; width: 95%; margin: auto; padding: 15px;">
            <div style="float: left;">
                <%= image_tag("plant.jpg", size: "400x200") %>
                <% if current_user.plants.count < 6 %>
                    <div style="float:right;">
                        <h3 style="float: right; margin-top: 30px;">Carefully select which plant to propogate!</h3><br>
                        <p>(You can only have 6 plants!)</p>

                        <%= form_for @plant, url: { action: "create" } do |f| %>
                            <%= f.label :id, text="Select a plant:"%>
                            <%= f.collection_select :id, @plants, :id, :description %><br><br>

                            <%= f.submit text="Propogate!"%>
                        <% end %>
                    </div>

                <% else %>
                    <h3 style="float: right; margin-top: 50px;">You can't have any more plants!</h3>
                <% end %>
            </div>
        </div><br>

    <h2 style="margin-left: 50px;">Your Plants</h2>
    <div class="row" style="border: solid; border-width: 1px; width: 95%; margin: auto; padding: 15px;">
        <div class="row">
            <% @plants.each do |plant| %>
            <% if @plants.count == 1 %>
                <div class="single-plant">
            <% elsif @plants.count == 2 %>
                <div class="two-plants">
            <% else %>
                <div class="many-plants">
            <% end %>
                    <% if plant.nickname == nil || plant.nickname == "" %>
                        <div style="margin-top: 78px;"></div>
                    <% else %>
                        <h1><i><%= plant.nickname %></i></h1>
                    <% end %>
                        <% if plant.stat_total >= 70 %>
                            <div class="profile-picture"><a href="<%= plant_path(plant) %>"><%= image_tag("happy.jpg") %></a></div>
                        <% else %>
                            <div class="profile-picture"><a href="<%= plant_path(plant) %>"><%= image_tag("sad.jpeg") %></a></div>
                        <% end %>
                    <h3>~ <%= plant.name %> ~</h3>
                    <p>Health: <%= plant.health %></p>
                    <p>Happiness: <%= plant.happiness %></p>
                    <p>Hunger: <%= plant.hunger %></p>
                </div>
            <% end %>
        </div>
    </div>

<% else %>

    <div class="home-page-image"><%= image_tag("sad-cloud.gif") %></div>
    <div style="text-align: center; margin-top: 100px;">
        <h3>You must be signed in to view your plants!</h3>
        <br>
        <h3><%= link_to "log in", '/login' %> or <%= link_to "sign up", new_user_path %></h3>
    </div>

<% end %>

app/views/plants/show.html.erb
<div class="row">
    <% if @plant.nickname != "" && @plant.nickname != nil %>
        <h1 style="margin-top: 39px; text-align: center;"><i><%= @plant.nickname %>, the <%= @plant.name %> plant</i></h1>
    <% else %>
        <h1 style="margin-top: 39px; text-align: center;"><i><%= @plant.name %></i></h1>
    <% end %>

    <div class="column-left">
        <div class="profile-picture" style="text-align: center; margin-top: 20px;">
            <% if @plant.stat_total >= 70 %>
                <div class="profile-picture"><%= image_tag("happy.jpg") %></div>
            <% else %>
                <div class="profile-picture"><%= image_tag("sad.jpeg") %></div>
            <% end %>
            <h3>~ <%= @plant.name %> ~</h3><br>
            Health Status: <%= @plant.stat_total %>%<br>
            Resilience: <%= @plant.resilience %><br>

            <% if @plant.user.id == session[:user_id] %>
                <br>Owned by you!<br>
                <%= link_to "Edit Plant", edit_plant_path(@plant) %>
            <% else %>
                <br>Owned by: <%= link_to @plant.user.username, user_path(@plant.user) %>
            <% end %>
        </div>
    </div>

    <div class="column-right">
        <div style="margin-top: 25px; margin-right: 150px; margin-bottom: 250px;">
            
            <div class="action-picture column" style="text-align: center;">
                <%= image_tag("food.png") %><br><br>
                <div class="w3-container">
                    <div class="w3-light-grey w3-round-xlarge">
                        <div class="w3-container w3-blue w3-round-xlarge" style="width:<%= @plant.hunger %>%"><%= @plant.hunger %>%</div>
                    </div>
                </div><br>
                <button style="padding: 0px;"><a href="/plants/<%= @plant.id %>/feed"><h4 style="margin-left: 18px; margin-right: 18px;">Give Food</h4></a></button>
            </div>

            <div class="action-picture column" style="text-align: center;">
                <%= image_tag("sun.png") %><br><br>
                <div class="w3-container">
                    <div class="w3-light-grey w3-round-xlarge">
                        <div class="w3-container w3-blue w3-round-xlarge" style="width:<%= @plant.happiness %>%"><%= @plant.happiness %>%</div>
                    </div>
                </div><br>
                <button style="padding: 0px;"><a href="/plants/<%= @plant.id %>/sun"><h4 style="margin-left: 18px; margin-right: 18px;">Put In Window</h4></a></button>
            </div>

            <div class="action-picture column" style="text-align: center;">
                <%= image_tag("water.png") %><br><br>
                <div class="w3-container">
                    <div class="w3-light-grey w3-round-xlarge">
                        <div class="w3-container w3-blue w3-round-xlarge" style="width:<%= @plant.health %>%"><%= @plant.health %>%</div>
                    </div>
                </div><br>
                <button style="padding: 0px;"><a href="/plants/<%= @plant.id %>/water"><h4 style="margin-left: 18px; margin-right: 18px;">Give Water</h4></a></button>
            </div>
        </div>

        <div style="margin-top: 75px;">
            <h4>About <%= @plant.name %> plants:</h4>
            <% if @plant.name == "Moss" %>
                <p style="width: 90%;">Moss-type plants are usually bright green in color. Some species can be pale green (almost white), bluish-green,
                    yellowish-green or velvety black green. Unlike most other plants, mosses do not have vascular tissue (a special
                    kind of plant tissue that is used to transport water and nutrients through the plant).</p>
            <% elsif @plant.name == "Flower" %>
                <p style="width: 90%;">A flower, sometimes known as a bloom or blossom, is the reproductive structure found in flowering plants. Flowers
                    provide an eye-catching attribute to an otherwise plain, green-leaved plant. In their range of color, size, form,
                    and anatomical arrangement, flowers present a seemingly endless variety of combinations. They range in size from
                    minute blossoms to giant blooms. There are even some bioluminescent orchids that emit a greenish-white light, not
                    just from the petals but also from the roots, stem, and leaves, which is a constant light visible to the human eye,
                    lasting up to 5 hours at a time.</p>           
            <% elsif @plant.name == "Fern" %>
                <p style="width: 90%;">Ferns-type plants are a vascular, seedless plant that belong to the group Pteridophyta. There are around 12,000
                    types of ferns that differ in size, morphology and type of habitat. Ferns can be found throughout the world. They
                    live in shady places that provide enough moisture, such as forests, fields, swamps and areas near the streams.
                    Fern can survive in various climates and on different altitudes. These plants are among the oldest living organisms
                    on the planet. People use ferns mostly in decorative purposes. Several types of ferns are known as invasive species
                    due to increased reproduction rate and ability to occupy new habitats quickly. Some species of ferns are listed as
                    endangered because of the habitat loss (as a result of increased human activity).</p>
            <% else %>
                <p style="width: 90%;">Succulents are plants with fleshy, thick tissues adapted to water storage. There are over 60 different succulent
                    families and about 10,000 plant variants that differ in color, texture, and size. Other than Antarctica, succulents
                    can be found within each continent. But most succulents come from Africa and South and Central America. Succulents
                    have the ability to thrive on limited water sources, such as mist and dew, which makes them equipped to survive in an
                    ecosystem which contains scarce water sources. They are found in nearly all types of habitat, but most often in arid or
                    semi-arid parts of the world.</p>
            <% end %>
        </div>

        <div class="row" style="border: solid; border-width: 1px; padding: 20px; margin-right: 50px; margin-top: 30px;">
            <h4 style="margin-top: 0px; margin-bottom: 20px;"><u>Care Log</u></h4>  
            <% @plant.care_actions.last(5).reverse.each do |c| %>
                <% if c.time_elapsed < 200 %>
                    <b><%= c.user.username %></b><br>
                    <%= c.time_elapsed %> minutes ago.<br>
                    <%= c.action.name %> - <%= c.action.effect %><br><br>
                <% end %>
            <% end %>
        </div>
        <br><br>
        This plant is <%= @plant.age %> and was created on <%= @plant.created_at.strftime("%B %d, %Y at %I:%M %p") %>
        <br>
    </div>
</div>