config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :messages, only: [:new, :create]
  end
  resources :plants, except: [:destroy]
  resources :friendships
  resources :messages, only: [:index, :show]
  
  get "/", to: 'users#home'
  # get "/messages", to: 'users#comingsoon'

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#logout"

  get "/plants/new", to: "plants#index"
  get "/plants/:id/water", to: "plants#water"
  get "/plants/:id/feed", to: "plants#feed"
  get "/plants/:id/sun", to: "plants#sun"

  get "/users/:id/add-friend", to: "friend_requests#create"
  get "/users/:id/remove-friend", to: "friendships#destroy"
  
  get "/friendships/:id/accept-request", to: "friend_requests#update"
  get "friendships/:id/deny-request", to: "friend_requests#destroy"
  get "friendships/:id/destroy", to: "friendships#destroy"
end

app/views/layouts/_error_list.html.erb
<% if new_object.errors %>
    <div style="display: inline-block;"
        <ul>
            <% new_object.errors.full_messages.each do |message| %>
                <p style="color: red;"><%= message %></p>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div>
    <ul>
        <a href="/">
            <div class="box">
                <h5 style="margin-top: 14px; margin-bottom: 0px; float: left; margin-left: 18px;">Bio</h5>
                <h5 style="margin-top: 0px; float: right; margin-right: 20px;">Plants</h5>
            </div>
        </a>

<% if session[:user_id] %>

            <li class="dropdown">
                <a href="<%= user_path(current_user) %>" class="dropbtn"><h4>Profile</h4></a>
                    <div class="dropdown-content">
                        <a href="<%= user_path(current_user) %>">My Profile</a>
                        <a href="<%= users_path %>">All Profiles</a>
                    </div>
                </li>
            <li><a href="<%= plants_path %>"><h4>Plants</h4></a></li>
            <li><a href="<%= friendships_path %>"><h4>Friends</h4></a></li>
            <li><a href="/messages"><h4>Messages</h4></a></li>
            <li style="float:right"><a class="active" href="/logout"><h4>Log Out</h4></a></li>
        </ul>
    </div>

<% else %>

            <li><a href="<%= users_path %>"><h4>Profile</h4></a></li>
            <li><a href="<%= plants_path %>"><h4>Plants</h4></a></li>
            <li style="float:right"><a class="active" href="/login"><h4>Log In</h4></a></li>
        </ul>
    </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BioPlants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #eeeeee;">
    <%= render "layouts/navigation" %>
    <div class="content-box">
      <br>
      <%= yield %>
      <br class="clear">
    </div>
  </body>
</html>